name: 'Run Elastic Enterprise Search'
description: 'This action spins up an Elasticsearch instance with Elastic Enterprise Search that can be accessed and used in your subsequent steps.'
author: 'elastic'

branding:
  icon: 'search'
  color: 'green'

inputs:
  stack-version:
    description: 'The version of the Elastic Stack you want to run'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    STACK_VERSION: ${{ inputs.stack-version }}
