name: 'Run Elasticsearch'
description: 'This action spins up an Elasticsearch instance that can be accessed and used in your subsequent steps.'
author: 'elastic'

branding:
  icon: 'database'
  color: 'green'

inputs:
  stack-version:
    description: 'The version of the Elastic Stack you want to run'
    required: true
  security-enabled:
    description: 'Enable or disable HTTPS, enabled by default'
    default: 'true'
    required: false
  nodes:
    description: 'Number of nodes in the cluster'
    required: false
    default: 1
  port:
    description: 'Port where you want to run Elasticsearch'
    required: false
    default: 9200
  elasticsearch_password:
    description: 'The password for the user elastic in your cluster'
    required: false
    default: 'changeme'
  plugins:
    description: 'Plugins that you want to include'
    required: false
  wait:
    description: 'Number of seconds to wait after launch'
    required: false
    default: 10
  network-name:
    description: 'Name of the network to create with docker'
    required: false
    default: elastic

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    STACK_VERSION: ${{ inputs.stack-version }}
    NODES: ${{ inputs.nodes }}
    PORT: ${{ inputs.port }}
    PLUGINS: ${{ inputs.plugins }}
    SECURITY_ENABLED: ${{ inputs.security-enabled }}
    ELASTICSEARCH_PASSWORD: ${{ inputs.elasticsearch_password }}
    WAIT: ${{ inputs.wait }}
    NETWORK_NAME: ${{ inputs.network-name }}
